### ISSUE TITLE
сделать тестовое приложение

### ISSUE THREAD

**Issue by AnnushkaEbaka** [DaerioFrixell/setting-webpack-config#2]
использовать React, TS, react-route-dom, Axios, Lazy-components

**Comment by Katsuri-dev** [comment]
react, ts работает уже

**Comment by Katsuri-dev** [comment]
reac-router-dom подключен и использован

**Comment by Katsuri-dev** [comment]
Axios подключен

**Comment by Katsuri-dev** [comment]
Lazy-components добавил
